services:
  mysql:
    image: mysql:8.4
    container_name: tradehub-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tradehub_db
      MYSQL_USER: tradehub_user
      MYSQL_PASSWORD: tradehub_password
    ports:
      - "3307:3306"
    volumes:
      - tradehub_mysql_data:/var/lib/mysql

volumes:
  tradehub_mysql_data: